# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "ahci"
    "nvme"
    "usbhid"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-intel"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/370f4e02-897c-4627-b9f2-f2d7a43cd441";
    fsType = "btrfs";
    options = ["subvol=rootfs"];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/370f4e02-897c-4627-b9f2-f2d7a43cd441";
    fsType = "btrfs";
    options = ["subvol=nix"];
  };

  fileSystems."/.swap" = {
    device = "/dev/disk/by-uuid/370f4e02-897c-4627-b9f2-f2d7a43cd441";
    fsType = "btrfs";
    options = ["subvol=swap"];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/370f4e02-897c-4627-b9f2-f2d7a43cd441";
    fsType = "btrfs";
    options = ["subvol=home"];
  };

  fileSystems."/boot/efi" = {
    device = "/dev/disk/by-uuid/5B7C-45D3";
    fsType = "vfat";
    options = [
      "fmask=0022"
      "dmask=0022"
    ];
  };

  fileSystems."/media/storage" = {
    device = "/dev/disk/by-uuid/b1cc5a58-b7f6-4138-a707-29b532368844";
    fsType = "btrfs";
  };

  swapDevices = [];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno1.useDHCP = lib.mkDefault true;
  # networking.interfaces.tailscale0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp0s20f3.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
